# Generated by Django 3.2.23 on 2023-11-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='poli',
            field=models.CharField(choices=[('umum', 'Umum'), ('mulut/gigi', 'Mulut/Gigi'), ('lansia', 'Lansia'), ('pkpr', 'PKPR'), ('kia/kb', 'KIA/KB'), ('mtbm/mtbs', 'MTBM/MTBS')], max_length=50),
        ),
    ]
