# Generated by Django 3.2.23 on 2023-11-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
        migrations.DeleteModel(
            name='Apoteker',
        ),
    ]
