# Generated by Django 3.2.23 on 2023-11-03 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('poli', models.CharField(max_length=50)),
                ('asuransi', models.BooleanField(default=False)),
                ('status', models.CharField(default='belum_bayar', max_length=10)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.pasien')),
            ],
        ),
        migrations.CreateModel(
            name='Pemeriksaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keluhan', models.TextField()),
                ('suhu_tubuh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tensi_darah', models.CharField(max_length=10)),
                ('berat_badan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tinggi_badan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nadi_per_menit', models.CharField(max_length=10)),
                ('diagnosis', models.TextField()),
                ('intruksi', models.TextField()),
                ('alergi', models.TextField()),
                ('riwayat_penyakit', models.TextField()),
                ('resep', models.TextField()),
                ('otp', models.CharField(max_length=6)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pendaftaran')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalDokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=10)),
                ('waktu', models.CharField(max_length=10)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dokter')),
            ],
        ),
    ]
