# Generated by Django 3.2.22 on 2023-10-30 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('pasien', 'Pasien'), ('dokter', 'Dokter'), ('apoteker', 'Apoteker'), ('admin', 'Admin')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poli', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('no_telp', models.CharField(max_length=15)),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('pekerjaan', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('waktu', models.CharField(max_length=10)),
                ('poli', models.CharField(max_length=50)),
                ('asuransi', models.BooleanField(default=False)),
                ('status', models.CharField(default='menunggu', max_length=10)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pasien')),
            ],
        ),
        migrations.CreateModel(
            name='Pemeriksaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keluhan', models.TextField()),
                ('suhu_tubuh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tensi_darah', models.CharField(max_length=10)),
                ('berat_badan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tinggi_badan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nadi_per_menit', models.CharField(max_length=10)),
                ('diagnosis', models.TextField()),
                ('intruksi', models.TextField()),
                ('alergi', models.TextField()),
                ('riwayat_penyakit', models.TextField()),
                ('resep', models.TextField()),
                ('otp', models.CharField(max_length=6)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pendaftaran')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalDokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=10)),
                ('waktu', models.CharField(max_length=10)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.dokter')),
            ],
        ),
        migrations.CreateModel(
            name='Apoteker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
