# Generated by Django 3.2.23 on 2023-11-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='poli',
        ),
    ]
