# Generated by Django 3.2.23 on 2023-11-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
