# Generated by Django 3.2.23 on 2023-11-03 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pasien', 'Pasien'), ('dokter', 'Dokter'), ('apoteker', 'Apoteker'), ('resepsionis', 'Resepsionis'), ('admin', 'Admin')], max_length=15),
        ),
        migrations.CreateModel(
            name='Resepsionis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
