# Generated by Django 3.2.23 on 2023-11-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231110_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='id',
            field=models.IntegerField(default='iG1mqu', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='id',
            field=models.IntegerField(default='ocwkuw', editable=False, primary_key=True, serialize=False),
        ),
    ]
