# Generated by Django 3.2.23 on 2023-11-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_pemeriksaan_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='token',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
