# Generated by Django 3.2.23 on 2023-11-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_pendaftaran_waktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwaldokter',
            name='waktu',
            field=models.CharField(max_length=15),
        ),
    ]
