# Generated by Django 3.2.23 on 2023-11-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_jadwaldokter_waktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwaldokter',
            name='hari',
            field=models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu'), ('minggu', 'Minggu')], max_length=10),
        ),
    ]
