# Generated by Django 3.2.23 on 2023-11-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_pemeriksaan_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='is_full',
        ),
    ]
