# Generated by Django 3.2.23 on 2023-11-10 12:27

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20231110_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='id',
            field=models.CharField(default=base.models.random_pk, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='id',
            field=models.CharField(default=base.models.random_pk, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
