# Generated by Django 3.2.23 on 2023-11-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_jadwaldokter_hari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='status',
            field=models.CharField(choices=[('belum_bayar', 'Belum Bayar'), ('antre', 'Antre'), ('selesai', 'Selesai')], default='belum_bayar', max_length=15),
        ),
    ]
