# Generated by Django 3.2.23 on 2023-11-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_pendaftaran_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemeriksaan',
            name='otp',
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
